In [1]:
import pandas as pd

In [6]:
df = pd.read_csv("contatos - Página1.csv")
df

    nome           email
0   João   joao@mail.com
1  Maria  maria@mail.com
2   José   jose@mail.com

In [5]:
df = pd.read_csv("contatos - Página1.tsv", sep='\t')
df

    nome           email
0   João   joao@mail.com
1  Maria  maria@mail.com
2   José   jose@mail.com

In [8]:
df = pd.read_excel("contatos.xlsx")
df

    nome           email
0   João   joao@mail.com
1  Maria  maria@mail.com
2   José   jose@mail.com